spring:
  application:
    name: spring-cloud-example-gateway

server:
  port: 8002

# Eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true #是否以IP开头显示注册名
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
# eureka.instance.instance-id是使得服务实例在eureka界面显示注册名

# com.netflix.zuul.exception.zuulexception timeout 超时报错
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


